# Termi AI GitHub Pages Configuration
# This file configures Jekyll for GitHub Pages

# Site settings
title: Termi AI
description: Your AI-powered development companion - A desktop app that combines live project previews with intelligent AI assistance using Cursor Agent.
url: "https://baronjensen.github.io"
baseurl: "/cursovable"

# Author information
author:
  name: Termi AI Team
  email: hello@termi-ai.com
  bio: Building the future of AI-powered development
  location: Worldwide
  links:
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/BaronJensen/cursovable

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections and defaults removed for GitHub Pages compatibility

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - LICENSE
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - CHANGELOG.md

# Social media
social:
  - name: GitHub
    url: https://github.com/BaronJensen/cursovable
    icon: fab fa-github

# SEO settings
seo:
  title: Termi AI - Your AI-Powered Development Companion
  description: Combine live project previews with intelligent AI assistance using Cursor Agent. Available for macOS, Windows, and Linux.
  keywords:
    - termi ai
    - electron
    - react
    - vite
    - ai
    - development
    - cursor agent
    - desktop app
    - open source
  image: /assets/og-image.png
  type: website
  twitter:
    card: summary_large_image
    creator: "@termi-ai"
  og:
    type: website
    site_name: Termi AI

# Analytics (uncomment and configure as needed)
# google_analytics: UA-XXXXXXXXX-X
# google_tag_manager: GTM-XXXXXXX

# Comments (uncomment and configure as needed)
# disqus:
#   shortname: termi-ai

# Sitemap
sitemap:
  changefreq: weekly
  priority: 0.8

# Redirects
redirect_from:
  - /home
  - /about
  - /downloads
  - /docs

# Head and footer includes removed for GitHub Pages compatibility

# Custom variables
termi-ai:
  version: "0.1.0"
  latest_release: "2024-12-19"
  platforms:
    - macOS
    - Windows
    - Linux
  package_managers:
    - yarn
    - npm
    - pnpm
  features:
    - Live Project Preview
    - AI Development Assistant
    - Smart Terminal Integration
    - Cross-Platform Support
    - Persistent History
    - Responsive Design
